# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=auth-service
server.port=${SERVER_PORT:8081}

# ===============================
# SERVER PORT
# ===============================

# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:123456789}}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EUREKA CLIENT CONFIG
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey123}
jwt.expiration=${JWT_EXPIRATION:3600000}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.server.url=/

# ===============================
# LOGGING (OPTIONAL)
# ===============================
logging.level.org.springframework.security=DEBUG

# ===============================
# RESILIENCE4J CONFIG
# ===============================
resilience4j.circuitbreaker.instances.mentorService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.mentorService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.mentorService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.mentorService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.mentorService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.mentorService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.mentorService.eventConsumerBufferSize=10

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.endpoint.health.show-details=always

# ===============================
# DISTRIBUTED TRACING (ZIPKIN)
# ===============================
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.zipkin.tracing.export.enabled=${ZIPKIN_ENABLED:false}
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9412/api/v2/spans}
