# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=api-gateway
server.port=${SERVER_PORT:8080}

# ===============================
# SERVER PORT
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

# ===============================
# GATEWAY ROUTES & CORS
# ===============================
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*

spring.cloud.gateway.server.webflux.routes[0].id=auth-service-docs
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/v3/api-docs
spring.cloud.gateway.server.webflux.routes[0].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[1].id=user-service-docs
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/v3/api-docs
spring.cloud.gateway.server.webflux.routes[1].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[2].id=mentor-service-docs
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/mentors/v3/api-docs
spring.cloud.gateway.server.webflux.routes[2].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[3].id=skill-service-docs
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/skills/v3/api-docs
spring.cloud.gateway.server.webflux.routes[3].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[4].id=session-service-docs
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/sessions/v3/api-docs
spring.cloud.gateway.server.webflux.routes[4].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[5].id=group-service-docs
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/groups/v3/api-docs
spring.cloud.gateway.server.webflux.routes[5].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[6].id=review-service-docs
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/reviews/v3/api-docs
spring.cloud.gateway.server.webflux.routes[6].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[7].id=auth-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[8].id=user-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[9].id=mentor-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://MENTOR-SERVICE
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/mentors/**

spring.cloud.gateway.server.webflux.routes[10].id=session-service
spring.cloud.gateway.server.webflux.routes[10].uri=lb://SESSION-SERVICE
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/sessions/**

spring.cloud.gateway.server.webflux.routes[11].id=group-service
spring.cloud.gateway.server.webflux.routes[11].uri=lb://GROUP-SERVICE
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/groups/**

spring.cloud.gateway.server.webflux.routes[12].id=review-service
spring.cloud.gateway.server.webflux.routes[12].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/reviews/**

spring.cloud.gateway.server.webflux.routes[13].id=skill-service
spring.cloud.gateway.server.webflux.routes[13].uri=lb://SKILL-SERVICE
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/skills/**

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=/users/v3/api-docs
springdoc.swagger-ui.urls[2].name=mentor-service
springdoc.swagger-ui.urls[2].url=/mentors/v3/api-docs
springdoc.swagger-ui.urls[3].name=skill-service
springdoc.swagger-ui.urls[3].url=/skills/v3/api-docs
springdoc.swagger-ui.urls[4].name=session-service
springdoc.swagger-ui.urls[4].url=/sessions/v3/api-docs
springdoc.swagger-ui.urls[5].name=group-service
springdoc.swagger-ui.urls[5].url=/groups/v3/api-docs
springdoc.swagger-ui.urls[6].name=review-service
springdoc.swagger-ui.urls[6].url=/reviews/v3/api-docs
