# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=group-service
server.port=${SERVER_PORT:8086}

# ===============================
# SERVER PORT
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:group_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:123456789}}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EUREKA CONFIG
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey123}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# Tracing & Observability
# ===============================
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.zipkin.tracing.export.enabled=${ZIPKIN_ENABLED:false}
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9412/api/v2/spans}
springdoc.server.url=/
management.endpoints.web.exposure.include=health,info,prometheus,zipkin
