# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=user-service
server.port=${SERVER_PORT:8082}

# ===============================
# SERVER PORT
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:123456789}}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EUREKA CLIENT CONFIG
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey123}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# LOGGING (OPTIONAL)
# ===============================
logging.level.org.springframework.web=DEBUG

# ===============================
# RESILIENCE4J CONFIG
# ===============================
resilience4j.circuitbreaker.instances.userService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.eventConsumerBufferSize=10

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.endpoint.health.show-details=always

# ===============================
# DISTRIBUTED TRACING (ZIPKIN)
# ===============================
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.zipkin.tracing.export.enabled=${ZIPKIN_ENABLED:false}
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9412/api/v2/spans}
springdoc.server.url=/
