# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=session-service
server.port=${SERVER_PORT:8085}

# ===============================
# SERVER PORT
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:session_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:123456789}}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EUREKA CONFIG
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}

# ===============================
# RABBITMQ CONFIG
# ===============================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# ===============================
# QUEUE CONFIG (CUSTOM)
# ===============================
rabbitmq.exchange=${RABBITMQ_EXCHANGE:session.exchange}
rabbitmq.queue=${RABBITMQ_QUEUE:session.queue}
rabbitmq.routingkey=${RABBITMQ_ROUTING_KEY:session.routingkey}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
