# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=eureka-server

# ===============================
# SERVER PORT
# ===============================
server.port=8761

# ===============================
# EUREKA CONFIG
# ===============================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false